# Generated by Django 3.1.2 on 2021-05-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=70)),
                ('companyName', models.CharField(max_length=70)),
                ('imageUrl', models.URLField()),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
