# Generated by Django 3.1.2 on 2021-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('userEmail', models.CharField(max_length=64)),
                ('userPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
