# Generated by Django 3.1.2 on 2021-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userProducts',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
